// src/routes/__layout.svelte
<script>
	import Navbar from '../components/Navbar.svelte';
	import Footer from '../components/Footer.svelte';

	let links = [
		{ href: '/', name: 'Home' },
		{ href: '/about', name: 'About' },
		{ href: '/board', name: 'Meet the Board' },
		{ href: '/register', name: 'JOIN ASU' }
	];
</script>

<div class="drawer p-0  mx-auto m-0 drawer-end">
	<input id="my-drawer-3" type="checkbox" class="drawer-toggle" />
	<div class="drawer-content flex flex-col">
		<div class="">
			<Navbar {links} />

			<div class="min-h-full">
				<slot />
			</div>

			<Footer />
		</div>
	</div>
	<div class="drawer-side">
		<label for="my-drawer-3" class="drawer-overlay" />
		<ul class="menu p-4 overflow-y-auto w-80 bg-base-100 justify-start">
			<!-- Sidebar content here -->
			{#each links as link}
				<li
					class={`max-w-sm py-3 justify-items-center text-2xl ${
						link.name === 'JOIN ASU' ? 'bg-[#79424C]' : null
					}`}
				>
					<a href={link.href}>{link.name}</a>
				</li>
			{/each}
		</ul>
	</div>
</div>

<style>
	@tailwind base;
	@tailwind components;
	@tailwind utilities;
</style>

// apps/events/src/components/Layout.tsx
import { BuiltInProviderType } from 'next-auth/providers';
import { ClientSafeProvider, getProviders, LiteralUnion } from 'next-auth/react';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import Footer from './Footer';
import LoginForm from './LoginForm';
import Navbar from './Navbar';

export default function Layout({ children }: { children?: React.ReactNode }) {
	const [providers, setProviders] = useState<Record<
		LiteralUnion<BuiltInProviderType, string>,
		ClientSafeProvider
	> | null>(null);
	useEffect(() => {
		getProviders().then((providers) => setProviders(providers));
		console.log(providers);
	}, []);
	return (
		<div className="drawer  p-0 mx-auto m-0">
			<input id="my-drawer" type="checkbox" className="drawer-toggle" />
			<div className="drawer-content w-screen">
				<div className="min-h-screen bg-gradient-radial from-[#EBDCD0] to-base-100 min-w-full">
					<Head>
						<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
					</Head>
					<Navbar />
					<div className="min-h-full max-w-7xl mx-auto p-4">{children}</div>

					<Footer />
				</div>
			</div>
			<div className="drawer-side w-screen">
				<label htmlFor="my-drawer" aria-label="close sidebar" className="drawer-overlay"></label>
				<ul
					className="menu p-4 w-80 min-h-full bg-base-200 text-base-content"
					id="sidebar-content"
				></ul>
			</div>
		</div>
	);
}
